import React, { useEffect, useRef, useState } from "react";
import CanvasContainer from "../CanvasContainer";
import { Section6 } from "./Section6";
import { motion, AnimatePresence } from "framer-motion";

export const SectionProjektid = () => {

    return (
      <>
        <section className="projektid">
          <div className="projektid-content">
            <h1 className="medium-headline white-gradient" >Projektid</h1>
            <div className="projektid-containers">
              <div className="projektid-row" >
                <div className="projekt-box">
                  <i class="fa-solid fa-bars"></i>
                  <h1 className="description white-shade projektid-text-center" >Proactive blocklist tracking</h1>
                  <p className="small-text projektid-text-bottom" >Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </>
    )
}