/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/lnqCRIqwFx97lXaA/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#1e1e21']} />
      <group {...props} dispose={null}>
        <scene scale={ 0.5 } name="Scene">
          <mesh
            name="chips"
            geometry={nodes.chips.geometry}
            material={materials['Untitled Material']}
            castShadow
            receiveShadow
            rotation={[0, -0.56, -1.22]}
            scale={1}
          />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}






